services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:stable-alpine
        container_name: laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app
            - mysql
        environment:
            - NGINX_CLIENT_MAX_BODY_SIZE=10M

    mysql:
        image: mysql:8
        container_name: laravel_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jobnet_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - mysql
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"
        networks:
            - laravel

    mailhog:
        image: mailhog/mailhog
        container_name: laravel_mailhog
        ports:
            - "8025:8025"
        networks:
            - laravel

    vite:
        image: node:18
        working_dir: /app
        volumes:
            - ./:/app
        command: sh -c "npm install && npm run dev"
        ports:
            - "5173:5173"

networks:
    laravel:

volumes:
    dbdata:
